DELETE FROM ACCOUNT;
DELETE FROM ACCOUNT_HOLDER;

INSERT INTO ACCOUNT_HOLDER (ID, LOGIN, NAME, EMAIL) VALUES (1,'cocoa','Nick','test1@mail.ru');
INSERT INTO ACCOUNT_HOLDER (ID, LOGIN, NAME, EMAIL) VALUES (2,'arny','Anton','test2@mail.ru');
INSERT INTO ACCOUNT_HOLDER (ID, LOGIN, NAME, EMAIL) VALUES (3,'jolly','Stacy','test3@mail.ru');

INSERT INTO ACCOUNT (ID, DATE_PLACED, start_balance, owner_id) VALUES (1,'10.02.2017', '789.45',1);
INSERT INTO ACCOUNT (ID, DATE_PLACED, start_balance, owner_id) VALUES (2,'15.03.2017', '123.40',1);
INSERT INTO ACCOUNT (ID, DATE_PLACED, start_balance, owner_id) VALUES (3,'17.04.2017', '345.88',3);


