DELETE FROM account;
DELETE FROM user;

INSERT INTO ACCOUNT (DATE, BALANCE) VALUES ('10.02.2017', '789.45');
INSERT INTO ACCOUNT (DATE, BALANCE) VALUES ('15.03.2017', '123.40');
INSERT INTO ACCOUNT (DATE, BALANCE) VALUES ('17.04.2017', '345.88');

INSERT INTO USER (LOGIN, NAME, EMAIL) VALUES ('cocoa','Nick','test1@mail.ru');
INSERT INTO USER (LOGIN, NAME, EMAIL) VALUES ('arny','Anton','test2@mail.ru');
INSERT INTO USER (LOGIN, NAME, EMAIL) VALUES ('jolly','Stacy','test3@mail.ru');

